name: Deployment
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Build
      env:
        DOMAIN: explorer.libplanet.io
      run: |
        ./build.sh

    - name: Publish
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: _site/
        GH_PAT: ${{ secrets.GH_PAT }}

    - name: Trigger GitHub Pages Build
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        curl -X POST \
             -H "Authorization: token $GH_PAT" \
             -H "Accept: application/vnd.github.mister-fantastic-preview+json" \
             "https://api.github.com/repos/$GITHUB_REPOSITORY/pages/builds"
